name: go-workflow
on:
  push:
    # branches:
    #   - master
  pull_request:

jobs:
  golang-tests:
    name: tests
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      matrix:
        # TODO: We will need to figure out how to test against `master`
        go-version: ["1.13", "1.14", "1.15"]
        go111module: ["off"]
    env:
      GOPATH: ${{ github.workspace }}
      GO111MODULE: ${{ matrix.go111module }}
    defaults:
      run:
        working-directory: ${{ env.GOPATH }}/src/github.com/${{ github.repository }}
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version}}
      - uses: actions/checkout@v2
        with:
          path: ${{ env.GOPATH }}/src/github.com/${{ github.repository }}
      - name: Remove if Go Module mode
        run: |
          if [[ $GO111MODULE == off ]]; then
            # XXX: Do we need this variable for the next steps in the workflow?
            echo 'GOFLAGS="-mod=readonly"' >> $GITHUB_ENV
            # Iris is not supported in legacy GOPATH mode. We delete the source code
            # because otherwise lint, build, and test steps would fail.
            rm -vrf ./iris/ ./example/iris/
            # go get is not required in Module mode
            GOFLAGS="-mod=readonly" go get -v -t ./...
          fi
      - name: Build
        run: go build ./...
      - name: Tests
        run: |
          go test ./...
          go test ./... -race
  golang-lint:
    name: lint
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2.3.0
        with:
          # Required: the version of golangci-lint is required and must be specified without
          # patch version: we always use the latest patch version.
          version: v1.29