name: go-workflow
on:
  push:
    # branches:
    #   - master
  pull_request:

jobs:
  go-tests:
    name: tests
    runs-on: ubuntu-20.04
    timeout-minutes: 20
    strategy:
      matrix:
        # TODO: We will need to figure out how to test against `master`
        go-version: ["1.13", "1.14", "1.15"]
        go111module: ["on", "off"]

    env:
      GO111MODULE: ${{ matrix.go111module }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version}}
      - name: Install golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/v1.27.0/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.27.0
      - name: Remove if Go Module mode
        run: |
          if [[ $GO111MODULE == off ]]; then
            echo "GOFLAGS=-mod=readonly" >> $GITHUB_ENV
            # Iris is not supported in legacy GOPATH mode. We delete the source code
            # because otherwise lint, build, and test steps would fail.
            rm -vrf ./iris/ ./example/iris/
            # go get is not required in Module mode
            go get -v -t ./...
          fi
      # TODO: Failing with `fatal: Not a valid object name origin/master`
      # - name: Linting
      #   run: |
      #     golangci-lint run --new-from-rev=$(git merge-base origin/master HEAD)
      - name: Build
        run: go build ./...
      - name: Tests
        run: |
          go test ./...
          go test ./... -race